# Generated by Django 4.0.1 on 2022-06-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_categoryy_productt_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='productt',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='productt',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categoryy',
        ),
        migrations.DeleteModel(
            name='Productt',
        ),
    ]
