# Generated by Django 4.0.1 on 2022-06-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_artiles_anons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
